version: "3.5"

services:
  shop:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      POSTGRES_HOST: pg
    ports:
      - 8000:8000
    volumes:
      - ./shop:/var/app
    depends_on:
      - pg

  pg:
    image: postgres:11
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
    - ./pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
